# Site settings
title: RudCloud
description: Une solution cloud pour la maison
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: RudCloud
user_description: Grace à RudCloud vous pouvez héberger une solution de cloud chez vous à la maison et ainsi rester propriétaire de vos données.
user_title: Notre solution cloud pour la maison
email: rudcloudfr@gmail.com
github_username:  rudcloud
medium_url: rudcloud.fr

exclude: ['package.json', 'src', 'node_modules', 'vendor']

